/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MessagePrinter */

#ifndef _Included_MessagePrinter
#define _Included_MessagePrinter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MessagePrinter
 * Method:    printMsg
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_MessagePrinter_printMsg
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
